
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using System.Reflection;


// Wholy generated by ChatGPT :D

#if UNITY_EDITOR
using UnityEditor;

public class TypeSelectorAttribute : PropertyAttribute
{
    // This attribute can be used to mark properties that should display their type in the inspector.
    // It does not require any additional fields or properties.
}

[CustomPropertyDrawer(typeof(TypeSelectorAttribute))]
public class TypeSelectorPropertyDrawer : PropertyDrawer
{
    private static Dictionary<Type, Type[]> _typeCache = new();

    public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
    {
        EditorGUI.BeginProperty(position, label, property);

        if (property.propertyType != SerializedPropertyType.ManagedReference)
        {
            EditorGUI.LabelField(position, label.text, "Use [SerializeReference] with [TypeSelector]");
            EditorGUI.EndProperty();
            return;
        }

        // First line: foldout + type selector popup side by side
        float lineHeight = EditorGUIUtility.singleLineHeight;
        float spacing = EditorGUIUtility.standardVerticalSpacing;

        Rect foldoutRect = new Rect(position.x, position.y, 15, lineHeight);
        Rect typeButtonRect = new Rect(position.x + 15, position.y, position.width - 15, lineHeight);

        Type currentType = GetManagedReferenceType(property);
        string currentTypeName = currentType != null ? currentType.Name : "None";

        property.isExpanded = EditorGUI.Foldout(foldoutRect, property.isExpanded, GUIContent.none, true);

        if (GUI.Button(typeButtonRect, $"{label.text}: {currentTypeName}", EditorStyles.popup))
        {
            GenericMenu menu = new GenericMenu();
            Type baseType = GetFieldBaseType(fieldInfo);
            Type[] types = GetAssignableTypes(baseType);

            menu.AddItem(new GUIContent("None"), currentType == null, () =>
            {
                property.managedReferenceValue = null;
                property.serializedObject.ApplyModifiedProperties();
            });

            foreach (Type type in types)
            {
                string menuLabel = type.FullName.Replace('.', '/');
                menu.AddItem(new GUIContent(menuLabel), type == currentType, () =>
                {
                    property.managedReferenceValue = Activator.CreateInstance(type);
                    property.serializedObject.ApplyModifiedProperties();
                    property.isExpanded = true;
                });
            }

            menu.ShowAsContext();
        }

        // Draw child properties if expanded
        if (property.isExpanded && property.managedReferenceValue != null)
        {
            EditorGUI.indentLevel++;
            float currentY = position.y + lineHeight + spacing;

            SerializedProperty child = property.Copy();
            SerializedProperty end = child.GetEndProperty();

            child.NextVisible(true);
            while (!SerializedProperty.EqualContents(child, end))
            {
                float childHeight = EditorGUI.GetPropertyHeight(child, true);
                Rect childRect = new Rect(position.x, currentY, position.width, childHeight);
                EditorGUI.PropertyField(childRect, child, true);
                currentY += childHeight + spacing;
                child.NextVisible(false);
            }

            EditorGUI.indentLevel--;
        }

        EditorGUI.EndProperty();
    }

    public override float GetPropertyHeight(SerializedProperty property, GUIContent label)
    {
        float height = EditorGUIUtility.singleLineHeight;

        if (property.isExpanded && property.managedReferenceValue != null)
        {
            SerializedProperty child = property.Copy();
            SerializedProperty end = child.GetEndProperty();

            child.NextVisible(true);
            while (!SerializedProperty.EqualContents(child, end))
            {
                height += EditorGUI.GetPropertyHeight(child, true) + EditorGUIUtility.standardVerticalSpacing;
                child.NextVisible(false);
            }
        }

        return height;
    }

    private Type GetManagedReferenceType(SerializedProperty property)
    {
        if (property.managedReferenceValue == null)
            return null;
        return property.managedReferenceValue.GetType();
    }

    private static Type[] GetAssignableTypes(Type baseType)
    {
        if (baseType == null)
            return Array.Empty<Type>();

        if (_typeCache.TryGetValue(baseType, out var cached))
            return cached;

        var types = AppDomain.CurrentDomain.GetAssemblies()
            .SelectMany(a =>
            {
                try { return a.GetTypes(); }
                catch { return Array.Empty<Type>(); }
            })
            .Where(t => baseType.IsAssignableFrom(t) && !t.IsAbstract && !t.IsInterface)
            .ToArray();

        _typeCache[baseType] = types;
        return types;
    }

    private static Type GetFieldBaseType(System.Reflection.FieldInfo field)
    {
        // Handles generic field definitions, e.g., List<BaseType>
        if (field.FieldType.IsGenericType && field.FieldType.GetGenericArguments().Length > 0)
            return field.FieldType.GetGenericArguments()[0];

        return field.FieldType;
    }
}


[CustomEditor(typeof(MonoBehaviour), true)]
public class TypeSelectorListEditor : Editor
{
    public override void OnInspectorGUI()
    {
        serializedObject.Update();

        var iterator = serializedObject.GetIterator();
        bool enterChildren = true;
        while (iterator.NextVisible(enterChildren))
        {
            enterChildren = false;

            // Draw normally if not a list of SerializeReference
            if (!ShouldDrawCustom(iterator))
            {
                EditorGUILayout.PropertyField(iterator, true);
                continue;
            }

            // Custom draw SerializeReference list
            DrawReferenceList(iterator);
        }

        serializedObject.ApplyModifiedProperties();
    }

    private bool ShouldDrawCustom(SerializedProperty prop)
    {
        return prop.isArray && prop.propertyType == SerializedPropertyType.Generic && IsManagedReferenceArray(prop);
    }

    private bool IsManagedReferenceArray(SerializedProperty prop)
    {
        if (prop.arraySize == 0)
            return false;

        var firstElement = prop.GetArrayElementAtIndex(0);
        return firstElement.propertyType == SerializedPropertyType.ManagedReference;
    }

    private void DrawReferenceList(SerializedProperty listProp)
    {
        EditorGUILayout.LabelField(ObjectNames.NicifyVariableName(listProp.name), EditorStyles.boldLabel);

        for (int i = 0; i < listProp.arraySize; i++)
        {
            SerializedProperty element = listProp.GetArrayElementAtIndex(i);
            EditorGUILayout.BeginVertical(GUI.skin.box);
            DrawManagedReference(element, listProp, i);
            EditorGUILayout.EndVertical();
        }

        if (GUILayout.Button("Add Element"))
        {
            listProp.arraySize++;
        }
    }

    private void DrawManagedReference(SerializedProperty element, SerializedProperty listProp, int index)
    {
        Type currentType = element.managedReferenceValue?.GetType();
        string currentTypeName = currentType?.Name ?? "None";

        EditorGUILayout.BeginHorizontal();
        element.isExpanded = EditorGUILayout.Foldout(element.isExpanded, $"Element {index}: {currentTypeName}");

        if (GUILayout.Button("Change Type", GUILayout.Width(100)))
        {
            Type baseType = GetFieldBaseType(listProp.name, listProp.serializedObject.targetObject.GetType());
            Type[] types = GetAssignableTypes(baseType);

            GenericMenu menu = new GenericMenu();

            foreach (var t in types)
            {
                menu.AddItem(new GUIContent(t.Name), t == currentType, () =>
                {
                    listProp.GetArrayElementAtIndex(index).managedReferenceValue = Activator.CreateInstance(t);
                    listProp.serializedObject.ApplyModifiedProperties();
                });
            }

            menu.ShowAsContext();
        }

        EditorGUILayout.EndHorizontal();

        if (element.isExpanded && element.managedReferenceValue != null)
        {
            EditorGUI.indentLevel++;
            var end = element.GetEndProperty();
            SerializedProperty child = element.Copy();
            child.NextVisible(true);
            while (!SerializedProperty.EqualContents(child, end))
            {
                EditorGUILayout.PropertyField(child, true);
                child.NextVisible(false);
            }
            EditorGUI.indentLevel--;
        }
    }

    private static Type[] GetAssignableTypes(Type baseType)
    {
        return AppDomain.CurrentDomain.GetAssemblies()
            .SelectMany(a => SafeGetTypes(a))
            .Where(t => baseType.IsAssignableFrom(t) && !t.IsAbstract)
            .ToArray();
    }

    private static IEnumerable<Type> SafeGetTypes(Assembly asm)
    {
        try { return asm.GetTypes(); }
        catch { return Array.Empty<Type>(); }
    }

    private static Type GetFieldBaseType(string fieldName, Type targetType)
    {
        var field = targetType.GetField(fieldName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
        if (field == null)
            return typeof(object);
        if (field.FieldType.IsGenericType)
            return field.FieldType.GetGenericArguments()[0];
        return field.FieldType;
    }
}

# else 
// if we are building for runtime, we don't need the editor code
// but we still need the attribute definition to avoid compilation errors

public class TypeSelectorAttribute : PropertyAttribute
{
    // This attribute can be used to mark properties that should display their type in the inspector.
    // It does not require any additional fields or properties.
}

public class TypeSelectorListEditor
{

}


# endif